catalog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    # индекс
    url(r'^$', views.index, name='index'),

    # urls на основе функций
    url(r'^documents/$', views.document_list, name='docs_list'),  # список документов
    path('document/<int:pk>', views.document, name='document'),  # конкретный документ
    url('document/(?P<pk>[0-9])/(?P<doc_version_id>[0-9])', views.document, name='document_version'),
    url(r'^addnew/$', views.document_add, name='document_add'),   # добавление документа
    url(r'^test/(?P<pk>[0-9])/(?P<doc_version_last_id>[0-9])/$', views.test, name='test'),   # тестовый шаблон
    url(r'^search/$', views.search, name='search'),   # поиск
    path('news/', views.news, name='news'),   # новости
    path('news/category/<int:category_id>', views.news, name='news_category'),   # новости категории
    path('news/<int:news_id>', views.news_view, name='news_view'),   # конкретная новость
 ]

catalog/models.py
from django.db import models
from django.urls import reverse


class Place(models.Model):
    place_issue = models.CharField(
        max_length=30,
        verbose_name="Место издания",
        help_text="Место издания"
    )

    def __str__(self):
        return self.place_issue

    class Meta:
        ordering = ('place_issue',)
        verbose_name = "Место издания документа"
        verbose_name_plural = "Места издания документов"


class DocStatus(models.Model):
    doc_status = models.CharField(
        max_length=30,
        verbose_name="Статус документа",
        help_text="Сведения о текущем статусе документа"
    )

    def __str__(self):
        return self.doc_status

    class Meta:
        # ordering = ('doc_status',)
        verbose_name = "Статус документа"
        verbose_name_plural = "Сведения о текущем статусе документа"


class DocType(models.Model):
    doc_type = models.CharField(
        max_length=30,
        verbose_name="Тип документа",
        help_text="Тип документа"
    )
    doc_imperative = models.CharField(
        max_length=30,
        verbose_name="Императив документа",
        help_text="Императив документа"
    )

    def __str__(self):
        return self.doc_type

    class Meta:
        ordering = ('doc_type',)
        verbose_name = "Тип документа"
        verbose_name_plural = "Типы документов"


# todo: предусмотреть хранение изменяющего документа
'''
Изменяющий документ хранить в основной модели документов:
Предусмотреть у основного документа статус "Изменяющий".
Приоритет поиска организовать с учетом статуса.
'''


class Document(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID документа")
    date_issue = models.DateField(verbose_name="Дата издания", help_text="Дата издания")
    doc_number = models.CharField(max_length=30, verbose_name="Номер документа", help_text="Номер документа")
    doc_title = models.TextField(verbose_name="Название", help_text="Название документа")
    position = models.CharField(max_length=40, verbose_name="Должность", help_text="Должность")
    rank = models.CharField(max_length=50, blank=True, verbose_name="Классный чин",
                            help_text="Классный чин должностного лица")
    fullname = models.CharField(max_length=30, verbose_name="Имя", help_text="Инициалы и фамилия должностного лица")
    # change = models.ForeignKey('self', null=True, on_delete=models.CASCADE)

    place_issue = models.ForeignKey(
        Place, verbose_name="Место издания",
        help_text="Место издания документа",
        on_delete=models.PROTECT
    )

    doc_type = models.ForeignKey(
        DocType,
        verbose_name="Тип документа",
        help_text="Тип документа",
        on_delete=models.PROTECT
    )

    doc_status = models.ForeignKey(
        DocStatus,
        verbose_name="Статус документа",
        help_text="Сведения о текущем статусе документа",
        on_delete=models.PROTECT,
    )

    class Meta:
        ordering = ('-date_issue',)
        verbose_name = "Основной документ"
        verbose_name_plural = "Основные документы"

    def __str__(self):
        return '%s от %s №%s' % (self.doc_type, self.date_issue, self.doc_number)

    def get_absolute_url(self):
        return reverse('document', args=(self.pk,))


class Control(models.Model):
    control_date = models.DateField(
        verbose_name="Контрольные даты",
        help_text="Контрольные даты",
        null=True
    )
    control_officer = models.CharField(
        max_length=40,
        verbose_name="Корреспондент контроля",
        help_text="Корреспондент контроля",
        null=True
    )

    control_doc = models.ForeignKey(
        Document,
        verbose_name="Контрольный документ",
        help_text="Контрольный документ",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.control_doc

    class Meta:
        ordering = ('control_date',)
        verbose_name = "Контрольная дата"
        verbose_name_plural = "Контрольные даты"


class DocVersion(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    date_version = models.DateField(verbose_name="Дата редакции", help_text="Дата редакции")
    date_start = models.DateField(verbose_name="Начало действия редакции", help_text="Начало действия редакции")
    preamble = models.TextField(blank=True, verbose_name="Преамбула", help_text="Преамбула документа")
    text = models.TextField(verbose_name="Текст документа", help_text="Текст документа")

    class Meta:
        ordering = ('-date_start',)
        verbose_name = "Версия документа"
        verbose_name_plural = "Версии документов"

    def __str__(self):
        return '%s от %s №%s (ред. от %s)' % \
               (self.document.doc_type,
                self.document.date_issue,
                self.document.doc_number,
                self.date_version
                )

    # def get_absolute_url(self):
    #     return reverse('catalog_docversion_detail', args=(self.pk,))


class News(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    content = models.TextField(blank=True, verbose_name='Контент')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото', blank=True)
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, null=True, verbose_name='Категория')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-created_at']


class Category(models.Model):
    title = models.CharField(max_length=150, db_index=True, verbose_name='Наименование направления работы')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Направление работы'
        verbose_name_plural = 'Направления работы'
        ordering = ['title']

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        <title>СПС "Документы"</title>
    {% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load bootstrap4 %}
    {%  comment %}
        <script src="{% bootstrap_jquery_url %}"></script>
    {% endcomment %}
    {% bootstrap_javascript %}
    {% bootstrap_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

{% include 'include/_navbar.html' %}

<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-md-2 mt-4">
            {% block sidebar %}
                {% include 'include/_sidebar.html' %}
            {% endblock %}
        </div>

        <div class="col-md-9 mt-4">
            {% block content %}CONTENT{% endblock %}
        </div>

        <div class="col-md-1 mt-4">
            {% block rightbar %}
                {% include 'include/_rightbar.html' %}
            {% endblock %}
        </div>

    </div>
</div>
</body>

</html>

catalog/templates/catalog/document_add.html
{% extends "catalog/base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <h5>Добавление нового документа (функция <b>document_add</b>)</h5>
    <p style="color: red">{{ error }}</p>
    <form method="post" action="document_add.html">
        {% csrf_token %}
        <p>
            <label for="id_date_issue">Дата документа:</label>
            <input type="date" name="date_issue" required id="id_date_issue">
            <span class="helptext">дата издания документа</span>
        </p>
        <p>
            <label for="id_doc_number">Номер документа:</label>
            <input type="text" name="doc_number" maxlength="30" required id="id_doc_number">
            <span class="helptext">Номер документа</span>
        </p>
{#        <p>#}
{#            <label for="id_place_issue">Место издания:</label>#}
{#            <select name="place_issue" required id="id_place_issue">#}
{#        </p>#}
        <p>
            <input type="submit" value="Опубликовать" />
        </p>
    </form>
{% endblock %}

catalog/templates/catalog/document_detail.html
{% extends "catalog/base_generic.html" %}
{#{% load bbcode_tags %}#}

{% block sidebar %}
    {% include 'include/_sidebar_docversions.html' %}
{% endblock sidebar %}

{% block content %}
    <h6>Служебная информация</h6>
    <div style="color: red">
        шаблон: document.html <b>(на основе функции)</b><br>
        переменная test: <b>{{ test }}</b><br>
        переменная pk: <b>{{ pk }}</b><br>
        переменная doc_actual_version_id: <b>{{ doc_actual_version_id }}</b><br>
        переменная doc_version_id: <b>{{ doc_version_id }}</b><br>
        переменная doc_version.date_version: <b>{{ doc_version.date_version }}</b><br>
    </div>
    <div style="text-align: center;">
        ПРОКУРАТУРА РОССИЙСКОЙ ФЕДЕРАЦИИ<br>
        ПРОКУРАТУРА АЛТАЙСКОГО КРАЯ
        <h5 class="mt-4 mb-4">{{ document.doc_type|upper }}</h5>
    </div>
    <table style="height: 18px; width: 100%; border-collapse: collapse;">
        <tbody>
        <tr style="height: 18px;">
            <td style="width: 50%; height: 18px;">{{ document.date_issue }}</td>
            <td style="width: 50%; height: 18px; text-align: right;">{{ document.doc_number }}</td>
        </tr>
        </tbody>
    </table>
    <div style="text-align: center;">
        {{ document.place_issue }}
    </div>
    <div style="text-align: center;" class="mt-4">
        <strong>{{ document.doc_title|safe }}</strong>

    </div>
    <div style="text-align: center;">
        <i>
            {% if doc_actual_version_id == doc_version_id %}
                (действующая редакция от {{ doc_version.date_version }})
            {% else %}
                <b style="color: red">(недействующая редакция от {{ doc_version.date_version }})</b><br>
                <a href="{% url 'document_version' pk=doc_version.document_id doc_version_id=doc_actual_version_id %}">
                    перейти в действующую
                </a>

            {% endif %}
        </i>
    </div>
    </p>
    <p style="text-align: justify;">{{ doc_version.preamble|safe }}</p>

    <h6 class="mt-4 mb-4" style="text-align: center;">{{ imperative|upper }}:</h6>

    {{ doc_version.text|safe }}

    <div class="mt-5 mb-5">
        <table style="width: 100%; border-collapse: collapse;" border="0">
            <tbody>
            <tr>
                <td style="width: 50%;">{{ document.position }}</td>
                <td style="width: 50%;">&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 50%;">{{ document.rank }}</td>
                <td style="width: 50%; text-align: right;">{{ document.fullname }}</td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

catalog/templates/catalog/documents_list.html
{# Список документов (на основе функции document_list) #}

{% extends "catalog/base_generic.html" %}

{% block sidebar %}
{% include 'include/_sidebar_doctype.html' %}
{% endblock %}

{% block content %}
    <h5>Список документов (на основе функции <b>document_list</b>)</h5>
    <br>
    {% include "include/_document_search.html" %}
    <br>
    <ul>
        {% for doc in doc_list %}
            <li>
                <a href="{% url 'document' pk=doc.pk %}">
                    {{ doc.doc_type }} от {{ doc.date_issue }} №{{ doc.doc_number }}
                    ({{ doc.doc_status }})</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h5>Справочно-правовая система <em>"Документы"</em> прокуратуры Алтайского края.</h5>
    <br>
    {% include "include/_document_search.html" %}
    <br>
    <p>Количество доступных документов: {{ num_docs }}</p>
{% endblock %}

catalog/templates/catalog/search_result.html
{% extends "catalog/base_generic.html" %}
{% block content %}
    <h2>СПС "Документы"</h2>
    <p>Справочно-правовая система <em>"Документы"</em> прокуратуры Алтайского края.</p>
    <br>
    <form action="search" method="get">
        <input type="text" name="q" size="80">
        <input type="submit" value="Найти документ">
    </form>
    <br>
    <p>Результаты поиска по запросу: {{ query }}</p>
    <ul>
    {% if doc_list %}
        {% for doc in doc_list %}
            <li>
                <a href="{% url 'document' pk=doc.pk %}">
                    {{ doc.doc_type }} от {{ doc.date_issue }} №{{ doc.doc_number }} ({{ doc.doc_status }})</a>
            </li>
        {% endfor %}
    {% else %}
    <h3>Нет результатов</h3>
    {% endif %}
</ul>
{% endblock %}

catalog/templates/catalog/test.html
{# тестовый шаблон #}

{% extends "catalog/base_generic.html" %}

{% block content %}
    <h5>Тестовый шаблон</h5>
    pk={{ pk }}
    <br>
    doc_version_last_id={{doc_version_last_id}}
{% endblock %}